# Generated by Django 4.0.3 on 2023-04-14 21:52

from django.db import migrations,models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_donor_userdata'),
    ]

    operations = [
         migrations.AddField(
            model_name='donor',
            name='contact',
            field=models.CharField(max_length=20, null=True),)
    ]
