# Generated by Django 4.0.3 on 2023-04-14 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_add_contact_to_donor_app'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='contact',
            field=models.CharField(default='1234567890', max_length=10),
        ),
        migrations.AlterField(
            model_name='donor',
            name='contact',
            field=models.CharField(default='1234567890', max_length=10),
        ),
    ]
