# Generated by Django 4.0.3 on 2023-04-14 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_userdata_contact_alter_donor_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donor',
            name='contact',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='contact',
            field=models.CharField(max_length=10),
        ),
    ]
